admin/urls.py
# -*- coding: utf-8 -*-

from django.conf import settings
from djangoplus.docs.views import doc
from django.views.static import serve
from djangoplus.core.views import cloud
from django.conf.urls import include, url
from djangoplus.docs.views import homologate

urlpatterns = [

    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    url(r'^cloud/(?P<path>.*)$', cloud, {'document_root': settings.MEDIA_ROOT}),

    url(r'^doc/$', doc),
    url(r'^homologate/$', homologate),

    url(r'', include('djangoplus.ui.components.calendar.urls')),
    url(r'', include('djangoplus.ui.components.navigation.urls')),
    url(r'', include('djangoplus.ui.components.select.urls')),

    url(r'', include('djangoplus.core.urls')),

]

admin/forms.py
# -*- coding: utf-8 -*-

import sys
import datetime
from django.core import signing
from django.contrib import auth
from django.conf import settings
from djangoplus.cache import CACHE
from djangoplus.ui.components import forms
from django.utils.translation import ugettext as _
from django.contrib.auth.hashers import make_password
from djangoplus.ui.components.navigation.breadcrumbs import httprr
from djangoplus.admin.models import Group, User, Unit, Settings, Organization


class LoginForm(forms.Form):
    
    ORGANIZATION = 'organization'
    UNIT = 'unit'
    
    username = forms.CharField(label=_('User'))
    password = forms.PasswordField(label=_('Password'))

    def __init__(self, request, scope=None, organization=None, unit=None, *args, **kwargs):
        super(LoginForm, self).__init__(request, *args, **kwargs)
        self.scope = None
        self.fields['username'].widget.attrs['class'] = 'input-sm bounceIn animation-delay2'
        if scope:
            if scope == LoginForm.ORGANIZATION or scope == (
                    CACHE['ORGANIZATION_MODEL'] and CACHE['ORGANIZATION_MODEL'].__name__.lower()):
                if organization:
                    self.scope_display = organization
                else:
                    organizations = Organization.objects.all()
                    self.fields['login_scope'] = forms.ModelChoiceField(organizations)
                self.scope = LoginForm.ORGANIZATION
            elif scope == LoginForm.UNIT or scope == (CACHE['UNIT_MODEL'] and CACHE['UNIT_MODEL'].__name__.lower()):
                if unit:
                    self.scope_display = unit
                else:
                    if organization:
                        self.scope_display = organization
                        units = organization.get_units()
                    else:
                        units = Unit.objects.all()
                    self.fields['login_scope'] = forms.ModelChoiceField(units)
                self.scope = LoginForm.UNIT
        self.organization = organization
        self.unit = unit

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError(_('User not registered.'))
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            if user.active:
                user.permission_mapping = ''
                user.organization = None
                user.unit = None
                if self.scope == LoginForm.ORGANIZATION:
                    user.organization = cleaned_data.get('login_scope', self.organization)
                    is_organization_user = user.role_set.filter(scope__in=(user.organization, 0)).exists()
                    if not is_organization_user:
                        raise forms.ValidationError('{} {} {}'.format(username, _('is not user of'), user.organization))
                elif self.scope == LoginForm.UNIT:
                    user.unit = cleaned_data.get('login_scope', self.unit)
                    is_unit_user = user.role_set.filter(scope__in=(user.unit, 0)).exists()
                    is_organization_user = CACHE['ORGANIZATION_MODEL'] and user.role_set.filter(
                        scope__in=(user.unit.get_organization(), 0)).exists()
                    if not is_unit_user and not is_organization_user:
                        raise forms.ValidationError('{} {} {}'.format(username, _('is not user of'), user.unit))
                else:
                    roles = user.role_set.all()
                    if roles.count() == 1:
                        role = roles.first()
                        if role.scope:
                            user.scope = role.scope
                user.save()
                auth.login(self.request, user)
                return cleaned_data
            else:
                raise forms.ValidationError(_('User is inactive.'))
        else:
            raise forms.ValidationError(_('Password is incorrect.'))

    def submit(self):
        url = self.request.GET.get('next', '/admin/')
        return httprr(self.request, url, _('You have successfully logged in.'))


class GroupForm(forms.ModelForm):
    name = forms.CharField(label='Name')

    class Meta:
        title = '{} {}'.format(_('Register'), _('Group'))
        submit_label = _('Save')
        icon = 'fa-users'
        model = Group
        fields = ('name',)


class UserForm(forms.ModelForm):
    is_superuser = forms.BooleanField(label=_('Superuser'), required=False)
    new_password = forms.PasswordField(label=_('Password'), required=False)

    class Meta:
        model = User
        fields = ('username', 'name', 'active', 'email', 'is_superuser', 'photo')
        title = '{} {}'.format(_('Register'), _('User'))
        submit_label = _('Save')
        icon = 'fa-user'

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        if not args[0].user.is_superuser:
            del (self.fields['is_superuser'])
            self.fieldsets = (
                (_('Identification'), {'fields': (('name', 'email',), 'photo')}),
                (_('Access'), {'fields': (('username', 'new_password'), ('active',))}),
            )
        else:
            self.fieldsets = (
                (_('Identification'), {'fields': (('name', 'email',), 'photo')}),
                (_('Access'), {'fields': (('username', 'new_password'), ('active', 'is_superuser'))}),
            )

    def save(self, *args, **kwargs):
        user = super(UserForm, self).save(commit=False)
        if 'new_password' in self.cleaned_data and self.cleaned_data['new_password']:
            user.set_password(self.cleaned_data['new_password'])
        user.save()


class RegisterForm(forms.Form):
    name = forms.CharField(label=_('Name'), required=True)
    email = forms.EmailField(label=_('E-mail'), required=True)
    new_password = forms.PasswordField(label=_('Password'), required=True)
    confirm_password = forms.PasswordField(label=_('Password'), required=True, help_text=_('Repeat Password'))

    class Meta:
        title = 'Novo Usuário'
        icon = 'fa-user'
        submit_label = 'Cadastrar'
        captcha = True

    fieldsets = (
        (_('User Data'), {'fields': ('name', 'email')}),
        (_('Access Password'), {'fields': (('new_password', 'confirm_password'),)}),
    )

    def clean(self):
        if not self.data['new_password'] == self.data['confirm_password']:
            raise forms.ValidationError(_('The passwords must be the same.'))
        return self.cleaned_data

    def save(self, *args, **kwargs):
        create = True
        user = User()
        password = self.cleaned_data['new_password']
        user.name = self.cleaned_data['name']
        user.email = self.cleaned_data['email']
        user.username = self.cleaned_data['email']
        user.active = True
        user.is_superuser = False
        user.last_login = None
        user.date_joined = datetime.datetime.now()
        user.username = user.email
        user.set_password(password)
        if create:
            user.save()
            return user
        else:
            token = signing.dumps('{};{};{}'.format(user.name, user.email, password))
            url = '{}/admin/create_user/{}/'.format(settings.SERVER_ADDRESS, token)
            msg = '{}: {}'.format(_('Click on the link to activate your account'), url), settings.SYSTEM_EMAIL_ADDRESS
            user.email_user(_('Account Activation'), msg)
            return None


class ChangePasswordForm(forms.ModelForm):
    new_password = forms.PasswordField(label=_('Password'), required=True)
    confirm_password = forms.PasswordField(label=_('Confirm Password'), required=True, help_text=_('Repeat the password'))

    fieldsets = ((_('Password'), {'fields': ('new_password', 'confirm_password',)}),)

    class Meta:
        model = User
        fields = ('id',)
        title = _('Change Password')
        submit_label = _('Save')
        icon = 'fa-key'

    def clean(self):
        if not self.data.get('new_password') == self.data.get('confirm_password'):
            raise forms.ValidationError(_('The passwords must be the same.'))
        return self.cleaned_data

    def save(self, *args, **kwargs):
        super(ChangePasswordForm, self).save(*args, **kwargs)
        User.objects.filter(pk=self.instance.pk).update(password=make_password(self.cleaned_data['new_password']))
        user = auth.authenticate(username=self.instance.username, password=self.cleaned_data['new_password'])
        auth.login(self.request, user)


class RecoverPassowordForm(forms.Form):
    email = forms.EmailField(label='E-mail')

    class Meta:
        captcha = 'test' not in sys.argv

    def clean(self):
        cleaned_data = super(RecoverPassowordForm, self).clean()
        qs = User.objects.filter(
            email=cleaned_data['email']
        )
        if qs.exists():
            qs.first().send_reset_password_notification()
            return cleaned_data
        else:
            raise forms.ValidationError(_('User not found.'))


class ProfileForm(forms.ModelForm):
    new_password = forms.PasswordField(label=_('Password'), required=False)
    confirm_password = forms.PasswordField(label=_('Confirm Password'), required=False, help_text=_('Repeat the password'))

    class Meta:
        model = User
        fields = ('name', 'photo', 'username', 'email')
        title = _('Edit Profile')
        submit_label = _('Save')
        icon = 'fa-user'

    fieldsets = (
        (_('User Data'), {'fields': (('name', 'username'), 'email', 'photo')}),
        (_('Access Password'), {'fields': (('new_password', 'confirm_password'),)}),
    )

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)

admin/templates/login/base.html
{% extends "admin.html" %}

{% block extra_admin_head %}
    <script src="/static/js/jquery.mask.min-1.7.7.js"></script>
{% endblock %}
{% block body %}
    <body id="login-body">
        <div id="login-wrapper">
            <div class="text-center">
                <h2 class="fadeInUp animation-delay8" style="font-weight:bold">
                    {% if settings.logo %}
                        <img height="70px" id="login-icon" src="/media/{{ settings.logo }}" alt="Logotipo de {{ settings.initials }}" />
                    {% endif %}
                    <p class="text-shadow-white"><a href="/">{{ settings.initials|truncatechars(23) }}</a></p>

                </h2>
                {% if form.scope_display %}
                <h4 class="fadeInUp animation-delay8">{{ form.scope_display }}</h4>
                {% endif %}
            </div>
            <div class="login-widget animation-delay1">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div>
                             {{ title }}
                        </div>
                    </div>
                    <div class="panel-body">

                        {% if form.non_field_errors() %}
                        <div class="alert alert-danger">
                            {{ form.non_field_errors() }}
                        </div>
                        {% endif %}

                        {% block form %}

                        {% endblock %}
                    </div>
                </div><!-- /panel -->
                {% if settings.company %}
                    <div class="copyright" align="center">&copy; {{ settings.company }}</div>
                {% endif %}
            </div><!-- /login-widget -->
        </div><!-- /login-wrapper -->
    </body>
    {% if allow_social_login and can_register %}
        <!-- FACEBOOK https://developers.facebook.com/docs/facebook-login/web/ -->
        {% if facebook_auth_id %}
            <script>
                window.fbAsyncInit = function() {
                    FB.init({appId: '341337683304718',  cookie: true,  xfbml: true, version: 'v2.8'});
                    FB.AppEvents.logPageView();
                };
                (function(d, s, id){
                 var js, fjs = d.getElementsByTagName(s)[0];
                 if (d.getElementById(id)) {return;}
                 js = d.createElement(s); js.id = id;
                 js.src = "https://connect.facebook.net/en_US/sdk.js";
                 fjs.parentNode.insertBefore(js, fjs);
                }(document, 'script', 'facebook-jssdk'));

                function statusChangeCallback(response) {
                  if (response.status === 'connected') {
                    document.location.href = '/admin/register/'+response.authResponse.accessToken+'/'+response.authResponse.userID+'/';
                  }
                }
                function checkLoginState() { FB.getLoginStatus(function(response) { statusChangeCallback(response); });}
                function fb_login(){FB.login(function(response) {statusChangeCallback(response);}, {scope: 'public_profile,email'});}
            </script>
        {% endif %}

        <!-- GOOGLE http://usefulangle.com/post/55/google-login-javascript-api -->
        {% if google_auth_key and google_auth_id %}
            <script async defer src="https://apis.google.com/js/api.js" onload="this.onload=function(){};HandleGoogleApiLibrary()" onreadystatechange="if (this.readyState === 'complete') this.onload()"></script>
            <script>
                function HandleGoogleApiLibrary() {
                    gapi.load('client:auth2',  {
                        callback: function() {
                            gapi.client.init({
                                apiKey: '{{ google_auth_key }}',
                                clientId: '{{ google_auth_id }}',
                                scope: 'https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/plus.me'
                            }).then(
                                function(success) {},
                                function(error) {alert(error);}
                            );
                        },
                        onerror: function() {alert('Error');}
                    });
                }
                function gg_login(event){gapi.auth2.getAuthInstance().signIn().then(function(success) { document.location.href = '/admin/register/'+success.Zi.access_token+'/';}, function(error) {alert(error);});}
            </script>
        {% endif %}
    {% endif %}
{% endblock %}

admin/templates/login/login.html
{% extends "login/base.html" %}

{% block form %}

    <form id="login-form" method="POST" action="{{ request.get_full_path()  }}" class="ajax-form" novalidate>
        {% csrf_token %}

        {% if can_register %}
            <div class="social-login">
                <a href="#" onclick="fb_login();return false;">
                    <span class="fa fa-facebook" aria-hidden="true"></span>
                    <span class="sr-only">Facebook</span>
                </a>
                <a href="#" onclick="gg_login(event);return false;">
                    <span class="fa fa-google" aria-hidden="true"></span>
                    <span class="sr-only">Google</span>
                </a>
            </div>
        {% endif %}

        {% if form.login_scope %}
        <div class="form-group">
            {{ form.login_scope }}
            {{ form.login_scope.errors }}
        </div>
        {% endif %}

        <div class="form-group">
            <label>{{ _("Username") }}</label>
            {{ form.username }}
            {{ form.username.errors }}
        </div>
        <div class="form-group">
            <label>{{ _("Password") }}</label>
            <input type="password" id="id_password" name="password" placeholder="Senha" class="form-control input-sm bounceIn animation-delay4">
            {{ form.username.errors }}
        </div>
        <div class="form-group">
            <label class="label-checkbox inline">
                <input type="checkbox" class="regular-checkbox chk-delete" />
                <span class="custom-checkbox info bounceIn animation-delay4"></span>
            </label>
            {{ _("Remember") }}
        </div>

        <div class="seperator"></div>

        {{ captcha(form) }}

        <button class="btn btn-default btn-md bounceIn animation-delay5 pull-right" type="submit"><i class="fa fa-sign-in"></i> {{ _("Sign-in") }}</button>
        {% if can_register %}
        <a href="/admin/register/" class="bounceIn animation-delay5 pull-left popup" type="submit" style="margin-right: 10px"> {{ _("Sign-up") }}</a>
        {% endif %}
    </form>

    <div class="form-group">
        <a href="/admin/reset/">{{ _("Reset Password") }}</a>
    </div>

{% endblock %}

admin/templates/login/password.html
{% extends "login/base.html" %}


{% block form %}


                        <form id="login-form" method="POST" action="{{ request.path }}" class="ajax-form" novalidate>
                            {% csrf_token %}

                            <div class="form-group">
                                <label>{{ _("Password") }}</label>
                                <input type="password" id="id_new_password" name="new_password" placeholder="Senha" class="form-control input-sm bounceIn animation-delay4">
                                {{ form.new_password.errors }}
                            </div>

                            <div class="form-group">
                                <label>{{ _("Confirm Password") }}</label>
                                <input type="password" id="id_confirm_password" name="confirm_password" placeholder="Confirmação" class="form-control input-sm bounceIn animation-delay4">
                                {{ form.confirm_password.errors }}
                            </div>

                            <div class="seperator"></div>
                            <hr/>

                            <button class="btn btn-default btn-md bounceIn animation-delay5 pull-right" type="submit"><i class="fa fa-sign-in"></i> {{ _("Save") }}</button>

                        </form>

{% endblock %}

admin/templates/login/recover.html
{% extends "login/base.html" %}
{% load i18n %}

{% block form %}


                        <form id="login-form" method="POST" action="{{ request.path }}" class="ajax-form" novalidate>
                            {% csrf_token %}

                            <div class="form-group">
                                <label>E-mail</label>
                                <input type="text" id="id_email" name="email" placeholder="E-mail" class="form-control input-sm bounceIn animation-delay4" value="{{ form.data.email|default:"" }}">
                                {{ form.email.errors }}
                            </div>

                            <div class="seperator"></div>
                            <hr/>

                            {% captcha form %}

                            <button class="btn btn-default btn-md bounceIn animation-delay5 pull-right" type="submit"><i class="fa fa-mail-forward"></i> {% trans "Reset Password" %}</button>

                        </form>

{% endblock %}

admin/templates/login/reset.html
{% extends "login/base.html" %}


{% block form %}


                        <form id="login-form" method="POST" action="{{ request.path }}" class="ajax-form" novalidate>
                            {% csrf_token %}

                            <div class="form-group">
                                <label>E-mail</label>
                                <input type="text" id="id_email" name="email" placeholder="E-mail" class="form-control input-sm bounceIn animation-delay4" value="{{ form.data.email|default("") }}">
                                {{ form.email.errors }}
                            </div>

                            <div class="seperator"></div>
                            <hr/>

                            {{ captcha(form) }}

                            <button class="btn btn-default btn-md bounceIn animation-delay5 pull-right" type="submit"><i class="fa fa-mail-forward"></i> {{ _("Send E-mail") }}</button>

                        </form>

{% endblock %}